# docker-compose file for running paperless from the Docker Hub.
# This file contains everything paperless needs to run.
# Paperless supports amd64, arm and arm64 hardware.
#
# All compose files of paperless configure paperless in the following way:
#
# - Paperless is (re)started on system boot, if it was running before shutdown.
# - Docker volumes for storing data are managed by Docker.
# - Folders for importing and exporting files are created in the same directory
#   as this file and mounted to the correct folders inside the container.
# - Paperless listens on port 8000.
#
# SQLite is used as the database. The SQLite file is stored in the data volume.
#
# To install and update paperless with this file, do the following:
#
# - Copy this file as 'docker-compose.yml' and the files 'docker-compose.env'
#   and '.env' into a folder.
# - Run 'docker-compose pull'.
# - Run 'docker-compose run --rm webserver createsuperuser' to create a user.
# - Run 'docker-compose up -d'.
#
# For more extensive installation and update instructions, refer to the
# documentation.

services:
  redis:
    image: redis
    container_name: paperless-redis
    restart: unless-stopped

    networks:
      default:
        ipv4_address: 192.168.0.37
    volumes:
      - /volume1/docker/paperless/redis:/usr/local/etc/redis

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperlessngx
    restart: unless-stopped
    depends_on:
      - redis
      - gotenberg
      - tika
    ports:
      - 8000:8000
    volumes:
      - /volume1/docker/paperless/data:/usr/src/paperless/data
      - /volume1/docker/paperless/media:/usr/src/paperless/media
      - /volume1/docker/paperless/export:/usr/src/paperless/export
      - /volume1/docker/paperless/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://192.168.0.37:6379
      PUID: 1024
      PGID: 100
      USERMAP_UID: 1024
      USERMAP_GID: 100
      PAPERLESS_TIME_ZONE: Europe/Berlin
      PAPERLESS_ADMIN_USER: admin
      PAPERLESS_ADMIN_PASSWORD: GEHEIM
      PAPERLESS_OCR_LANGUAGE: deu+eng
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://192.168.0.35:3000
      PAPERLESS_TIKA_ENDPOINT: http://192.168.0.36:9998
    networks:
        default:
            ipv4_address: 192.168.0.34

  gotenberg:
    image: gotenberg/gotenberg
    restart: unless-stopped
    container_name: gotenberg
    ports:
      - 3044:3000
    networks:
      default:
        ipv4_address: 192.168.0.35
    command:
      - "gotenberg"
      - "--chromium-disable-routes=true"

  tika:
    image: ghcr.io/paperless-ngx/tika
    container_name: tika
    ports:
      - 9998:9998
    networks:
      default:
        ipv4_address: 192.168.0.36
    restart: unless-stopped

networks:
  default:
    name: mvl
    external: true

# volumes:
#   data:
#   media:
#   redisdata:
