version: "3.7"
services:
  webserver:
    image: sissbruecker/linkding:latest
    container_name: linkding
    restart: unless-stopped
    ports:
      - ${LINKDING_PORT}:9090
    volumes:
      - ${VOLUME_DIR}/data:/etc/linkding/data
    env_file:
      - .env
    healthcheck:
      test:
        - CMD-SHELL
        - curl -f http://localhost:${LINKDING_PORT}/api/bookmarks | grep -q
          'bookmarks'
      interval: 30s
      timeout: 10s
      retries: 3
networks:
  linkding: {}
volumes:
  linkding_data: null
